name: Build and deploy
on: [push]
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '3.1.8'
